### ISSUE TITLE
sub-titles of grant, project, and publication cards broken

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#77] opened 2020-05-22 18:49 UTC
The sub-titles of grant, project, and publication cards seems to be displaying the name of the annotation column (institution, grantName, and authors, respectively) rather than the value itself.

Please see the attached screenshot -- I'm referring to "institution" under "Cancer Cell Map Initiative"

<img width="816" alt="grant-sub-title" src="https://user-images.githubusercontent.com/5123034/82699873-50677500-9c22-11ea-9ba5-6127a7e4e53b.png">

**Comment by jaeddy** [comment] 2020-05-22 19:04
@bswhite - it looks like something changed a couple hours ago in the `synapse-react-client` that changes how values and links in cards are rendered. I'm guessing the culprit is somewhere in this block of code (or in something related):

https://github.com/Sage-Bionetworks/Synapse-React-Client/blob/develop/src/lib/containers/GenericCard.tsx#L279-L286

@leem42 - Should we open a Jira for this bug?

**Comment by leem42** [comment] 2020-05-22 20:46
@bswhite @jaeddy Thanks for pointing that out and the problematic code too! I made an [issue](https://sagebionetworks.jira.com/browse/PORTALS-1368) to track that. :man_facepalming:

**Comment by jaeddy** [comment] 2020-05-27 03:40
Confirmed that this is fixed on staging. Thanks, @leem42!

**Closed as completed by jaeddy** 2020-05-27 03:40 UTC
Labels: Bug, Portal-Config, Sage-Engineering
